/**
 * Built-in question bank — used to seed MongoDB on first run.
 * Covers: DSA, Frontend, Backend, HR, System Design, Behavioral, DevOps, Data Science, Full Stack.
 */

export const SEED_QUESTIONS = [
  // ─── DSA ────────────────────────────────────────────────────────────────────
  { category:'dsa', difficulty:'easy', tags:['arrays','iteration'], timeLimit:120,
    text:'What is the time complexity of accessing an element in an array by index?',
    expectedAnswer:'O(1) — direct index access is constant time.',
    keywords:['O(1)','constant','index'] },
  { category:'dsa', difficulty:'easy', tags:['strings','two-pointers'], timeLimit:180,
    text:'How would you check if a string is a palindrome?',
    expectedAnswer:'Use two pointers from both ends and compare characters, or reverse and compare. O(n) time.',
    keywords:['palindrome','two pointers','reverse','O(n)'] },
  { category:'dsa', difficulty:'medium', tags:['arrays','sliding-window'], timeLimit:240,
    text:'Explain the sliding window technique and when to use it.',
    expectedAnswer:'Use a window of fixed or variable size that slides over an array/string to avoid nested loops. Best for contiguous subarray/substring problems. O(n) time.',
    keywords:['sliding window','contiguous','subarray','O(n)'] },
  { category:'dsa', difficulty:'medium', tags:['trees','recursion'], timeLimit:240,
    text:'How do you find the height of a binary tree?',
    expectedAnswer:'Recursively: height = 1 + max(height(left), height(right)). Base case: null → -1 or 0. O(n) time.',
    keywords:['recursion','height','binary tree','O(n)'] },
  { category:'dsa', difficulty:'medium', tags:['hashmaps','frequency'], timeLimit:240,
    text:'How would you find the first non-repeating character in a string?',
    expectedAnswer:'Use a hashmap to count frequencies, then iterate the string to find the first char with frequency 1. O(n) time and space.',
    keywords:['hashmap','frequency','O(n)'] },
  { category:'dsa', difficulty:'hard', tags:['dynamic-programming'], timeLimit:300,
    text:'Explain dynamic programming and how it differs from recursion with memoization.',
    expectedAnswer:'DP builds solutions bottom-up using a table. Memoization (top-down) caches recursive results. Both avoid recomputation but DP avoids call stack overhead and is often faster in practice.',
    keywords:['dynamic programming','memoization','bottom-up','top-down','subproblems'] },
  { category:'dsa', difficulty:'hard', tags:['graphs','bfs','dfs'], timeLimit:300,
    text:'When would you use BFS vs DFS for graph traversal?',
    expectedAnswer:'BFS finds shortest path in unweighted graphs (level-by-level). DFS is better for detecting cycles, topological sort, and exploring all paths. BFS uses a queue; DFS uses a stack (or recursion).',
    keywords:['BFS','DFS','shortest path','queue','stack','cycle'] },

  // ─── Frontend ────────────────────────────────────────────────────────────────
  { category:'frontend', difficulty:'easy', tags:['css','box-model'], timeLimit:120,
    text:'Explain the CSS box model.',
    expectedAnswer:'Every element has content, padding, border, and margin. Box-sizing: border-box includes padding and border in the width/height calculation.',
    keywords:['content','padding','border','margin','box-sizing'] },
  { category:'frontend', difficulty:'easy', tags:['react','hooks'], timeLimit:180,
    text:'What is the difference between useState and useEffect in React?',
    expectedAnswer:'useState manages state within a component. useEffect runs side effects after renders (data fetching, subscriptions, DOM mutations). Both are hooks.',
    keywords:['useState','useEffect','hooks','side effects','state'] },
  { category:'frontend', difficulty:'medium', tags:['javascript','closures'], timeLimit:240,
    text:'What is a closure in JavaScript and give a real-world use case.',
    expectedAnswer:'A closure is a function that retains access to its outer scope after the outer function has returned. Use case: private variables, memoization, event handlers with context.',
    keywords:['closure','scope','outer function','private','lexical'] },
  { category:'frontend', difficulty:'medium', tags:['react','virtual-dom'], timeLimit:240,
    text:'How does React\'s Virtual DOM improve performance?',
    expectedAnswer:'React creates a virtual copy of the DOM in memory. On state change, it diffs the new virtual DOM with the previous (reconciliation) and only updates changed real DOM nodes — reducing expensive DOM operations.',
    keywords:['virtual DOM','diffing','reconciliation','performance','real DOM'] },
  { category:'frontend', difficulty:'medium', tags:['javascript','event-loop'], timeLimit:240,
    text:'Explain the JavaScript event loop and how it handles async code.',
    expectedAnswer:'JS is single-threaded. The event loop checks the call stack, then processes the microtask queue (Promises), then the macrotask queue (setTimeout, I/O). This enables async non-blocking behavior.',
    keywords:['event loop','call stack','microtask','macrotask','Promise','setTimeout','single-threaded'] },
  { category:'frontend', difficulty:'hard', tags:['react','performance'], timeLimit:300,
    text:'How would you optimize a React app that re-renders too frequently?',
    expectedAnswer:'Use React.memo to prevent unnecessary child renders. Use useMemo for expensive calculations. Use useCallback for stable function references. Use code splitting (lazy + Suspense). Profile with React DevTools.',
    keywords:['React.memo','useMemo','useCallback','code splitting','profiling'] },

  // ─── Backend ─────────────────────────────────────────────────────────────────
  { category:'backend', difficulty:'easy', tags:['rest','http'], timeLimit:120,
    text:'What is the difference between PUT and PATCH in REST APIs?',
    expectedAnswer:'PUT replaces the entire resource with the provided data. PATCH applies a partial update — only the specified fields are changed.',
    keywords:['PUT','PATCH','resource','partial update','idempotent'] },
  { category:'backend', difficulty:'easy', tags:['databases','sql'], timeLimit:180,
    text:'What is the difference between SQL and NoSQL databases?',
    expectedAnswer:'SQL: structured, relational, ACID guarantees, fixed schema. NoSQL: flexible schema, various models (document/key-value/graph), horizontally scalable, eventual consistency by default.',
    keywords:['SQL','NoSQL','schema','ACID','relational','scalable'] },
  { category:'backend', difficulty:'medium', tags:['caching','redis'], timeLimit:240,
    text:'How would you implement caching in a backend API to improve performance?',
    expectedAnswer:'Use Redis or an in-memory cache (e.g. LRU cache). Cache expensive DB queries or API responses with a TTL. Use cache-aside, read-through, or write-through strategies. Invalidate on data mutation.',
    keywords:['Redis','cache','TTL','invalidation','LRU','strategy'] },
  { category:'backend', difficulty:'medium', tags:['authentication','jwt'], timeLimit:240,
    text:'How does JWT authentication work and what are its tradeoffs?',
    expectedAnswer:'JWT is a signed token (header.payload.signature). Server issues it after login; client sends it on every request. Stateless — no DB lookup needed. Tradeoff: cannot be revoked without a blocklist.',
    keywords:['JWT','stateless','signature','payload','revoke','claims'] },
  { category:'backend', difficulty:'hard', tags:['microservices','design'], timeLimit:300,
    text:'What are the main challenges of microservices architecture?',
    expectedAnswer:'Service discovery, inter-service communication (REST/gRPC/events), distributed tracing, data consistency across services, deployment complexity, network latency, and testing complexity.',
    keywords:['microservices','service discovery','distributed','gRPC','event-driven','latency'] },

  // ─── System Design ────────────────────────────────────────────────────────────
  { category:'system-design', difficulty:'medium', tags:['scalability','load-balancing'], timeLimit:300,
    text:'How would you design a URL shortener like bit.ly?',
    expectedAnswer:'Use a unique ID generator (base62 encoding), store [short_code → long_url] in a database, add Redis cache for hot URLs, use CDN for serving, handle redirects with 301/302. Scale with horizontal DB sharding.',
    keywords:['base62','hash','redirect','cache','sharding','CDN','unique ID'] },
  { category:'system-design', difficulty:'medium', tags:['databases','replication'], timeLimit:300,
    text:'Explain database replication and when to use it.',
    expectedAnswer:'Replication copies data to multiple nodes. Master-slave: writes go to master, reads distributed to replicas — improves read throughput and provides failover. Used for high availability and read scalability.',
    keywords:['replication','master','slave/replica','read scalability','failover','availability'] },
  { category:'system-design', difficulty:'hard', tags:['distributed-systems','cap-theorem'], timeLimit:360,
    text:'What is the CAP theorem and how does it affect distributed system design?',
    expectedAnswer:'CAP: a distributed system can only guarantee 2 of: Consistency (all reads see latest write), Availability (every request gets a response), Partition Tolerance (survives network splits). In practice, partitions happen, so you choose CP (e.g. RDBMS) or AP (e.g. Cassandra).',
    keywords:['CAP','consistency','availability','partition','distributed','Cassandra','tradeoff'] },
  { category:'system-design', difficulty:'hard', tags:['rate-limiting','api'], timeLimit:300,
    text:'How would you implement rate limiting for a public API?',
    expectedAnswer:'Use fixed window, sliding window, or token bucket algorithm. Store counters in Redis (fast, distributed). Key by user ID or IP. Return 429 with Retry-After header. Use a gateway like Kong or AWS API Gateway for centralized limiting.',
    keywords:['rate limiting','token bucket','sliding window','Redis','429','gateway'] },

  // ─── HR / Behavioral ─────────────────────────────────────────────────────────
  { category:'hr', difficulty:'easy', tags:['motivation','career'], timeLimit:180,
    text:'Tell me about yourself and your career journey so far.',
    expectedAnswer:'Structure: current role/skills → key achievements → why here now. Keep to 2 minutes. Focus on professional journey, not personal history.',
    keywords:['background','experience','achievements','skills','motivation'] },
  { category:'hr', difficulty:'easy', tags:['teamwork','collaboration'], timeLimit:180,
    text:'Describe a time you worked effectively in a team.',
    expectedAnswer:'Use STAR method: Situation (project context), Task (your role), Action (collaboration steps you took), Result (measurable outcome). Highlight communication and shared ownership.',
    keywords:['STAR','teamwork','collaboration','communication','outcome'] },
  { category:'hr', difficulty:'medium', tags:['conflict','problem-solving'], timeLimit:240,
    text:'Tell me about a conflict at work and how you resolved it.',
    expectedAnswer:'Use STAR. Focus on listening, understanding both perspectives, proposing a solution, and the positive outcome. Show emotional intelligence and professionalism.',
    keywords:['STAR','conflict','resolution','empathy','outcome','professional'] },
  { category:'hr', difficulty:'medium', tags:['failure','growth'], timeLimit:240,
    text:'Tell me about your biggest professional failure and what you learned.',
    expectedAnswer:'Be honest about a real failure. Focus on what you learned and how you changed behavior. Shows self-awareness, accountability, and growth mindset.',
    keywords:['failure','lesson','growth','accountability','reflection','improvement'] },
  { category:'hr', difficulty:'hard', tags:['leadership','influence'], timeLimit:300,
    text:'Describe a time you led a project without formal authority.',
    expectedAnswer:'Use STAR. Explain how you built consensus, communicated vision, delegated tasks, and drove results through influence rather than authority. Show leadership skills.',
    keywords:['leadership','influence','consensus','stakeholders','results','vision'] },

  // ─── DevOps ───────────────────────────────────────────────────────────────────
  { category:'devops', difficulty:'easy', tags:['docker','containers'], timeLimit:120,
    text:'What is Docker and how is it different from a virtual machine?',
    expectedAnswer:'Docker containers share the host OS kernel — lighter, faster startup. VMs have a full OS stack. Docker uses images/containers; VMs use hypervisors. Containers are ideal for microservices.',
    keywords:['Docker','container','VM','kernel','image','hypervisor','lightweight'] },
  { category:'devops', difficulty:'medium', tags:['kubernetes','orchestration'], timeLimit:240,
    text:'What problem does Kubernetes solve and what are its core components?',
    expectedAnswer:'K8s automates deployment, scaling, and management of containers. Core: Pod (smallest unit), Deployment (desired state), Service (networking), Ingress (routing), ConfigMap/Secret (config), Node/Cluster.',
    keywords:['Kubernetes','pod','deployment','service','orchestration','scaling','cluster'] },
  { category:'devops', difficulty:'medium', tags:['ci-cd','pipelines'], timeLimit:240,
    text:'Explain the difference between Continuous Integration, Delivery, and Deployment.',
    expectedAnswer:'CI: automatically build and test on every commit. CD (Delivery): code is always production-ready, deployed manually. CD (Deployment): fully automated deployment to production on every passing build.',
    keywords:['CI','CD','continuous integration','deployment','automation','pipeline','testing'] },
  { category:'devops', difficulty:'hard', tags:['infrastructure','terraform'], timeLimit:300,
    text:'What is Infrastructure as Code and what are its benefits?',
    expectedAnswer:'IaC defines infrastructure via code (Terraform, CloudFormation). Benefits: version control, reproducibility, consistency, faster provisioning, rollback capability, reduced manual error.',
    keywords:['IaC','Terraform','version control','reproducibility','Ansible','CloudFormation'] },

  // ─── Data Science / ML ────────────────────────────────────────────────────────
  { category:'data-science', difficulty:'easy', tags:['ml','supervised'], timeLimit:180,
    text:'What is the difference between supervised and unsupervised learning?',
    expectedAnswer:'Supervised: trains on labeled data to predict outputs (classification/regression). Unsupervised: finds patterns in unlabeled data (clustering, dimensionality reduction).',
    keywords:['supervised','unsupervised','labeled','classification','clustering','regression'] },
  { category:'data-science', difficulty:'medium', tags:['ml','overfitting'], timeLimit:240,
    text:'What is overfitting and how do you prevent it?',
    expectedAnswer:'Overfitting: model memorizes training data, performs poorly on new data (high variance). Prevent: regularization (L1/L2), dropout, cross-validation, early stopping, more training data.',
    keywords:['overfitting','regularization','dropout','cross-validation','variance','bias-variance'] },
  { category:'data-science', difficulty:'hard', tags:['ml','transformers'], timeLimit:300,
    text:'Explain the self-attention mechanism in transformer models.',
    expectedAnswer:'Self-attention computes a weighted sum of all token representations, where weights are based on query-key dot products (scaled and softmaxed). Allows the model to relate every token to every other token regardless of distance.',
    keywords:['self-attention','transformer','query','key','value','softmax','weights'] },
];

export const CATEGORY_DESCRIPTIONS = {
  dsa:            { title: 'DSA',            icon: '🧮', desc: 'Data Structures & Algorithms' },
  frontend:       { title: 'Frontend Dev',   icon: '💻', desc: 'React, CSS, JS, Browser APIs' },
  backend:        { title: 'Backend Dev',    icon: '⚙️',  desc: 'APIs, Databases, Architecture' },
  fullstack:      { title: 'Full Stack',     icon: '🌐', desc: 'End-to-end development' },
  'system-design':{ title: 'System Design',  icon: '🏗️', desc: 'Scalability, Architecture' },
  hr:             { title: 'HR / Behavioral',icon: '🤝', desc: 'Soft skills, STAR method' },
  behavioral:     { title: 'Behavioral',     icon: '💬', desc: 'Leadership, Teamwork, Growth' },
  devops:         { title: 'DevOps / Cloud', icon: '🔧', desc: 'CI/CD, Kubernetes, AWS' },
  'data-science': { title: 'Data Science',   icon: '📊', desc: 'ML, Stats, Python' },
  'product-manager':{ title: 'Product Manager', icon: '📋', desc: 'Strategy, Metrics' },
};
